alias gas="git add -A && git status"
alias gs="git status"
alias gpr="git pull -r"
alias grhh="git reset HEAD --hard"
alias gc="git commit -m"
alias echo2="echo $1 echo $2"
alias gcp="gas && git commit -m $1 && gpr && git push origin"
alias co="git checkout"
alias gdelbr="git co master && git branch | grep -v master | xargs git branch -D"
alias gcopm="git checkout master && git pull origin"
alias gcorm="git checkout master && git rebase origin"
alias gnewbr="git corm && git checkout -b"
alias gcleanbr="git branch -vv | grep ' gone]' | awk '{print $1}' | xargs git branch -D"
alias gstnewbr="git stash -u && git corm && git checkout -b $1 && git stash pop"
alias gpr="git pull -r && git log -15 --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)[%an]%Creset' --abbrev-commit"
alias grhh="git reset HEAD --hard"
alias gpo="git push -u origin HEAD"
alias gac="git as && git commit -m"
alias grh="git reset HEAD~"
alias gca="git commit --amend --no-edit"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"